from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pass_viewer', '0001_create_users_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS recaps
                (LIKE pass_objects INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES);

                ALTER TABLE recaps
                ADD COLUMN IF NOT EXISTS recap_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'recaps_pkey'
                    ) THEN
                        ALTER TABLE recaps
                        ADD CONSTRAINT recaps_pkey PRIMARY KEY (recap_id);
                    END IF;
                END
                $$;
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS recaps;
            """,
        ),
    ]
