from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pass_viewer', '0001_create_users_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE EXTENSION IF NOT EXISTS postgis;

                CREATE TABLE IF NOT EXISTS pass_objects (
                    rootid text NULL,
                    name text NULL,
                    "OwnerLegalPersonId" text NULL,
                    request_id text NULL,
                    geom geometry(Geometry, 4326) NOT NULL
                );

                CREATE INDEX IF NOT EXISTS pass_objects_geom_gix
                ON pass_objects
                USING GIST (geom);

                CREATE TABLE IF NOT EXISTS odh (
                    rootid text NULL,
                    name text NULL,
                    "CustomerLegalPersonId" text NULL,
                    request_id text NULL,
                    geom geometry(Geometry, 4326) NOT NULL
                );

                CREATE INDEX IF NOT EXISTS odh_geom_gix
                ON odh
                USING GIST (geom);

                CREATE TABLE IF NOT EXISTS recaps
                (LIKE pass_objects INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES);

                ALTER TABLE recaps
                ADD COLUMN IF NOT EXISTS recap_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'recaps_pkey'
                    ) THEN
                        ALTER TABLE recaps
                        ADD CONSTRAINT recaps_pkey PRIMARY KEY (recap_id);
                    END IF;
                END
                $$;
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS recaps;
            """,
        ),
    ]
