from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pass_viewer', '0003_create_id_names_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS ozn (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    rootid text NULL,
                    name text NULL,
                    descr text NULL,
                    address text NULL,
                    vri text NULL,
                    sobstv_rr text NULL,
                    properties jsonb NOT NULL DEFAULT '{}'::jsonb,
                    geom geometry(Geometry, 4326) NOT NULL
                );

                CREATE INDEX IF NOT EXISTS ozn_geom_gix
                ON ozn
                USING GIST (geom);
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS ozn;
            """,
        ),
    ]
