from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pass_viewer', '0006_add_ownerlegalpersonalid_to_ozn'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS renew (
                    pk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id text NULL,
                    code text NULL,
                    name text NULL,
                    status_code text NULL,
                    ext_status text NULL,
                    soon text NULL,
                    county text NULL,
                    district text NULL,
                    develop_address text NULL,
                    developer text NULL,
                    infocenter text NULL,
                    finishing_code text NULL,
                    vvod text NULL,
                    floors text NULL,
                    flats text NULL,
                    metro text NULL,
                    metro_walk text NULL,
                    metro_car text NULL,
                    anons_texts text NULL,
                    img text NULL,
                    geom geometry(Geometry, 4326) NOT NULL
                );

                CREATE INDEX IF NOT EXISTS renew_geom_gix
                ON renew
                USING GIST (geom);
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS renew;
            """,
        ),
    ]
