from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pass_viewer', '0012_create_hood_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS ods_request (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BrId" bigint NULL,
                    "BrStatusName" text NULL,
                    "CreateTypeName" text NULL,
                    "ReasonName" text NULL,
                    "PassportizationTypeName" text NULL,
                    "ObjectTypeName" text NULL,
                    "OwnerName" text NULL,
                    "GrbsName" text NULL,
                    "ShortObjectId" bigint NULL,
                    "ObjectName" text NULL,
                    "ObjectArea" double precision NULL,
                    "InspectionDatePlan" timestamptz NULL,
                    ownerid bigint NULL,
                    grbsid bigint NULL
                );
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS ods_request;
            """,
        ),
    ]
