from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pass_viewer", "0019_add_dgi_short_sobstv_rr"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS auto_remove_square (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "user" text NOT NULL,
                    ownerlegalpersonalid text NULL,
                    dt numeric(14, 1) NOT NULL DEFAULT 0,
                    odh numeric(14, 1) NOT NULL DEFAULT 0,
                    ozn numeric(14, 1) NOT NULL DEFAULT 0,
                    top numeric(14, 1) NOT NULL DEFAULT 0,
                    oozt numeric(14, 1) NOT NULL DEFAULT 0,
                    dgi numeric(14, 1) NOT NULL DEFAULT 0,
                    renew numeric(14, 1) NOT NULL DEFAULT 0,
                    rzd numeric(14, 1) NOT NULL DEFAULT 0,
                    summ numeric(14, 1) NOT NULL DEFAULT 0,
                    "type" text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('hour', CURRENT_TIMESTAMP)
                );
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS auto_remove_square;
            """,
        ),
    ]
