import uuid

import django.contrib.gis.db.models as gis_models
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


FORWARD_SQL = """
CREATE SCHEMA IF NOT EXISTS approval;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS approval.approves (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    incoming_guid uuid NOT NULL UNIQUE,
    owners text[] NOT NULL DEFAULT '{}',
    approved boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS approves_owners_gin
    ON approval.approves
    USING GIN (owners);

CREATE TABLE IF NOT EXISTS approval.cases (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    approve_id uuid NOT NULL REFERENCES approval.approves(id) ON DELETE CASCADE,
    is_primary boolean NOT NULL DEFAULT false,
    title text NOT NULL,
    status text NOT NULL DEFAULT 'в работе',
    created_by_login text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS cases_one_primary_per_approve
    ON approval.cases (approve_id)
    WHERE is_primary IS TRUE;

CREATE INDEX IF NOT EXISTS cases_approve_id_is_primary_idx
    ON approval.cases (approve_id, is_primary);

CREATE TABLE IF NOT EXISTS approval.case_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id uuid NOT NULL REFERENCES approval.cases(id) ON DELETE CASCADE,
    author_login text NOT NULL,
    author_role text NULL,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS case_messages_case_id_created_at_idx
    ON approval.case_messages (case_id, created_at);

CREATE TABLE IF NOT EXISTS approval.geometry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approve_id uuid NOT NULL REFERENCES approval.approves(id) ON DELETE CASCADE,
    case_id uuid NULL REFERENCES approval.cases(id) ON DELETE SET NULL,
    geom geometry(Geometry, 4326) NOT NULL,
    label text NULL,
    owner_legal_person_id text NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS geometry_geom_gix
    ON approval.geometry
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS geometry_approve_id_idx
    ON approval.geometry (approve_id);

CREATE OR REPLACE FUNCTION approval.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION approval.create_primary_case()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO approval.cases (approve_id, is_primary, title, status)
    VALUES (NEW.id, true, 'Основное событие', 'в работе');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_approves_create_primary_case ON approval.approves;
CREATE TRIGGER trg_approves_create_primary_case
    AFTER INSERT ON approval.approves
    FOR EACH ROW EXECUTE PROCEDURE approval.create_primary_case();

DROP TRIGGER IF EXISTS trg_approves_set_updated_at ON approval.approves;
CREATE TRIGGER trg_approves_set_updated_at
    BEFORE UPDATE ON approval.approves
    FOR EACH ROW EXECUTE PROCEDURE approval.set_updated_at();

DROP TRIGGER IF EXISTS trg_cases_set_updated_at ON approval.cases;
CREATE TRIGGER trg_cases_set_updated_at
    BEFORE UPDATE ON approval.cases
    FOR EACH ROW EXECUTE PROCEDURE approval.set_updated_at();
"""

REVERSE_SQL = """
DROP SCHEMA IF EXISTS approval CASCADE;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Approve",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("incoming_guid", models.UUIDField(unique=True)),
                        ("owners", ArrayField(base_field=models.TextField(), default=list, size=None)),
                        ("approved", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": '"approval"."approves"',
                    },
                ),
                migrations.CreateModel(
                    name="Case",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("is_primary", models.BooleanField(default=False)),
                        ("title", models.TextField()),
                        ("status", models.TextField(default="в работе")),
                        ("created_by_login", models.TextField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("closed_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "approve",
                            models.ForeignKey(
                                db_column="approve_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="cases",
                                to="approval.approve",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."cases"',
                    },
                ),
                migrations.CreateModel(
                    name="CaseMessage",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("author_login", models.TextField()),
                        ("author_role", models.TextField(blank=True, null=True)),
                        ("body", models.TextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "case",
                            models.ForeignKey(
                                db_column="case_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="messages",
                                to="approval.case",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."case_messages"',
                        "ordering": ["created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="ApprovalGeometry",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("geom", gis_models.GeometryField(srid=4326)),
                        ("label", models.TextField(blank=True, null=True)),
                        ("owner_legal_person_id", models.TextField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "approve",
                            models.ForeignKey(
                                db_column="approve_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="geometries",
                                to="approval.approve",
                            ),
                        ),
                        (
                            "case",
                            models.ForeignKey(
                                blank=True,
                                db_column="case_id",
                                null=True,
                                on_delete=models.deletion.SET_NULL,
                                related_name="geometries",
                                to="approval.case",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."geometry"',
                    },
                ),
            ],
        ),
    ]
