from django.db import migrations, models


FORWARD_SQL = """
ALTER TABLE approval.cases
    ADD COLUMN IF NOT EXISTS approved boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS approval.case_approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id uuid NOT NULL REFERENCES approval.cases(id) ON DELETE CASCADE,
    owner_legal_person_id text NOT NULL,
    approved_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (case_id, owner_legal_person_id)
);

CREATE INDEX IF NOT EXISTS case_approvals_case_id_idx
    ON approval.case_approvals (case_id);

CREATE TABLE IF NOT EXISTS approval.case_message_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES approval.case_messages(id) ON DELETE CASCADE,
    stored_name text NOT NULL,
    original_name text NOT NULL,
    content_type text NOT NULL,
    size_bytes bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS case_message_attachments_message_id_idx
    ON approval.case_message_attachments (message_id);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS approval.case_message_attachments;
DROP TABLE IF EXISTS approval.case_approvals;
ALTER TABLE approval.cases DROP COLUMN IF EXISTS approved;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0001_create_approval_schema"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="case",
                    name="approved",
                    field=models.BooleanField(default=False),
                ),
                migrations.CreateModel(
                    name="CaseApproval",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("owner_legal_person_id", models.TextField()),
                        ("approved_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "case",
                            models.ForeignKey(
                                db_column="case_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="approvals",
                                to="approval.case",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."case_approvals"',
                    },
                ),
                migrations.CreateModel(
                    name="CaseMessageAttachment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("stored_name", models.TextField()),
                        ("original_name", models.TextField()),
                        ("content_type", models.TextField()),
                        ("size_bytes", models.BigIntegerField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "message",
                            models.ForeignKey(
                                db_column="message_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="attachments",
                                to="approval.casemessage",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."case_message_attachments"',
                    },
                ),
                migrations.AddConstraint(
                    model_name="caseapproval",
                    constraint=models.UniqueConstraint(
                        fields=("case", "owner_legal_person_id"),
                        name="case_approvals_case_owner_uniq",
                    ),
                ),
            ],
        ),
    ]
