from django.db import migrations, models


FORWARD_SQL = """
CREATE TABLE IF NOT EXISTS approval.case_message_reactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES approval.case_messages(id) ON DELETE CASCADE,
    reactor_login text NOT NULL,
    kind text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (message_id, reactor_login)
);

CREATE INDEX IF NOT EXISTS case_message_reactions_message_id_idx
    ON approval.case_message_reactions (message_id);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS approval.case_message_reactions;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0006_inspector_and_case_roots"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CaseMessageReaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("reactor_login", models.TextField()),
                        (
                            "kind",
                            models.TextField(
                                choices=[
                                    ("in_progress", "В работе"),
                                    ("done", "Выполнено"),
                                ]
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "message",
                            models.ForeignKey(
                                db_column="message_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="reactions",
                                to="approval.casemessage",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."case_message_reactions"',
                    },
                ),
                migrations.AddConstraint(
                    model_name="casemessagereaction",
                    constraint=models.UniqueConstraint(
                        fields=("message", "reactor_login"),
                        name="case_message_reactions_message_reactor_uniq",
                    ),
                ),
            ],
        ),
    ]
