from django.db import migrations, models


FORWARD_SQL = """
CREATE TABLE IF NOT EXISTS approval.case_messages_deleted (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_message_id bigint NOT NULL,
    case_id uuid NOT NULL,
    author_login text NOT NULL,
    author_role text NULL,
    body text NOT NULL,
    parent_id bigint NULL,
    created_at timestamptz NOT NULL,
    deleted_at timestamptz NOT NULL DEFAULT now(),
    deleted_by_login text NOT NULL,
    attachments_json jsonb NULL
);

CREATE INDEX IF NOT EXISTS case_messages_deleted_case_id_idx
    ON approval.case_messages_deleted (case_id);

CREATE INDEX IF NOT EXISTS case_messages_deleted_original_message_id_idx
    ON approval.case_messages_deleted (original_message_id);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS approval.case_messages_deleted;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0010_case_message_reaction_verdict_kinds"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CaseMessageDeleted",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("original_message_id", models.BigIntegerField()),
                        ("case_id", models.UUIDField()),
                        ("author_login", models.TextField()),
                        ("author_role", models.TextField(blank=True, null=True)),
                        ("body", models.TextField()),
                        ("parent_id", models.BigIntegerField(blank=True, null=True)),
                        ("created_at", models.DateTimeField()),
                        ("deleted_at", models.DateTimeField(auto_now_add=True)),
                        ("deleted_by_login", models.TextField()),
                        ("attachments_json", models.JSONField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": '"approval"."case_messages_deleted"',
                        "ordering": ["-deleted_at"],
                    },
                ),
            ],
        ),
    ]
