from django.db import migrations, models


FORWARD_SQL = """
CREATE TABLE IF NOT EXISTS approval.case_service_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id uuid NOT NULL REFERENCES approval.cases(id) ON DELETE CASCADE,
    actor_login text NOT NULL,
    kind text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS case_service_events_case_id_idx
    ON approval.case_service_events (case_id);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS approval.case_service_events;
"""

MIGRATE_LEGACY_APPROVE_MESSAGES_SQL = """
INSERT INTO approval.case_service_events (case_id, actor_login, kind, created_at)
SELECT case_id, author_login, 'approved', created_at
FROM approval.case_messages
WHERE body = 'Событие согласовано.';

DELETE FROM approval.case_messages
WHERE body = 'Событие согласовано.';
"""


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0011_case_message_deleted"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
                migrations.RunSQL(
                    sql=MIGRATE_LEGACY_APPROVE_MESSAGES_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CaseServiceEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("actor_login", models.TextField()),
                        (
                            "kind",
                            models.TextField(
                                choices=[
                                    ("approved", "Согласовано"),
                                    ("revoked", "Отмена согласования"),
                                ]
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "case",
                            models.ForeignKey(
                                db_column="case_id",
                                on_delete=models.deletion.CASCADE,
                                related_name="service_events",
                                to="approval.case",
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"approval"."case_service_events"',
                        "ordering": ["created_at"],
                    },
                ),
            ],
        ),
    ]
