"""
Django settings for pass_map project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1av$uzw-*%0$zqq0@sxs8i87ru+ryy)yj*euj$x0c@lnv9gvq1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "axes",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pass_viewer",
    "approval",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "pass_viewer.middleware.HoodSpatialScopeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "pass_map.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pass_map.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _db_connect_timeout(env_name: str, default: str = "10") -> int:
    try:
        return int(os.getenv(env_name, default))
    except (TypeError, ValueError):
        return 10


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGIS_DB_NAME", "geodb"),
        "USER": os.getenv("POSTGIS_DB_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGIS_DB_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGIS_DB_HOST", "localhost"),
        "PORT": os.getenv("POSTGIS_DB_PORT", "5433"),
        "OPTIONS": {
            "connect_timeout": _db_connect_timeout("POSTGIS_DB_CONNECT_TIMEOUT"),
        },
    },
    "qgis": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("QGIS_DB_NAME", "mggt_asu"),
        "USER": os.getenv("QGIS_DB_USER", ""),
        "PASSWORD": os.getenv("QGIS_DB_PASSWORD", ""),
        "HOST": os.getenv("QGIS_DB_HOST", "172.21.197.51"),
        "PORT": os.getenv("QGIS_DB_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": _db_connect_timeout("QGIS_DB_CONNECT_TIMEOUT"),
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "pass_viewer.auth_backends.DockerUsersTableBackend",
]

# Brute-force protection for /accounts/login/ (django-axes).
AXES_ENABLED = os.getenv("AXES_ENABLED", "1") not in ("0", "false", "False")
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_LOCKOUT_TEMPLATE = "registration/lockout.html"


# PostGIS object source settings for map rendering.
GIS_OBJECT_TABLE = "pass_objects"
GIS_OBJECT_ROOTID_FIELD = "rootid"
GIS_OBJECT_NAME_FIELD = "name"
GIS_OBJECT_GEOM_FIELD = "geom"
GIS_OBJECT_OWNER_FIELD = "OwnerLegalPersonId"
# Реестр заявок (ODS), миграция 0013. Список на главной, фаза 1 — без геометрии.
GIS_ODS_REQUEST_TABLE = os.getenv("GIS_ODS_REQUEST_TABLE", "ods_request")
GIS_ODS_REQUEST_SOURCE_LABEL = os.getenv("GIS_ODS_REQUEST_SOURCE_LABEL", "ОДС")
# Справочник для расшифровки ID (home, popup). Таблица: см. миграцию 0003_create_id_names_table.
GIS_ID_NAMES_TABLE = os.getenv("GIS_ID_NAMES_TABLE", "id_names")

# Ограничение данных по районам (таблица hood, миграция 0012). Если таблицы нет — фильтр не включается.
GIS_HOOD_TABLE = os.getenv("GIS_HOOD_TABLE", "hood")
GIS_HOOD_ACCESS_ENABLED = os.getenv("GIS_HOOD_ACCESS_ENABLED", "1") not in ("0", "false", "False")
# Ограничение по районам (hood). При ACCESS=0 — выкл. Пространственные фильтры (WKT, ST_Intersects)
# выполняются только для пользователей с users.hood_scope=True (см. pass_viewer.hood_scope).
# Переменная GIS_HOOD_APPLY_SPATIAL_SCOPE оставлена для совместимости старых .env (не используется кодом).
GIS_HOOD_APPLY_SPATIAL_SCOPE = os.getenv("GIS_HOOD_APPLY_SPATIAL_SCOPE", "0") not in ("0", "false", "False")
# Мин. доля площади (0–1): пересечение union геометрий пользователя с районом / площадь union (geography, м²).
# Районы с меньшей долей не входят в hood-scope (срез «чуть-чуть» за границу). 0 = как раньше, любое ST_Intersects.
try:
    GIS_HOOD_MIN_OVERLAP_RATIO = float(os.getenv("GIS_HOOD_MIN_OVERLAP_RATIO", "0.05"))
except (TypeError, ValueError):
    GIS_HOOD_MIN_OVERLAP_RATIO = 0.05

GIS_OOZT_TABLE = os.getenv("GIS_OOZT_TABLE", "oozt")
GIS_RZD_TABLE = os.getenv("GIS_RZD_TABLE", "rzd")
GIS_TOP_TABLE = os.getenv("GIS_TOP_TABLE", "top")
GIS_TOP_SOURCE_LABEL = os.getenv("GIS_TOP_SOURCE_LABEL", "ТОП")
GIS_AUTO_REMOVE_SQUARE_TABLE = os.getenv("GIS_AUTO_REMOVE_SQUARE_TABLE", "auto_remove_square")
# Радиус nearby для всех объектов на карте (смежные ДТ, заявки, справочные слои).
try:
    GIS_ADJACENT_NEARBY_METERS = float(os.getenv("GIS_ADJACENT_NEARBY_METERS", "25"))
except (TypeError, ValueError):
    GIS_ADJACENT_NEARBY_METERS = 25.0

# На main: не грузить смежные ДТ и reference-слои в HTML — подгрузка через AJAX после открытия страницы.
GIS_DEFER_MAP_CONTEXT_LAYERS = os.getenv("GIS_DEFER_MAP_CONTEXT_LAYERS", "1")

# Упрощение линейных слоёв ООЗТ/РЖД при отдаче на карту (меньше точек → быстрее JSON).
try:
    GIS_OOZT_SIGNAL_SIMPLIFY_METERS = float(os.getenv("GIS_OOZT_SIGNAL_SIMPLIFY_METERS", "2"))
except (TypeError, ValueError):
    GIS_OOZT_SIGNAL_SIMPLIFY_METERS = 2.0
try:
    GIS_RZD_SIGNAL_SIMPLIFY_METERS = float(os.getenv("GIS_RZD_SIGNAL_SIMPLIFY_METERS", "5"))
except (TypeError, ValueError):
    GIS_RZD_SIGNAL_SIMPLIFY_METERS = 5.0
GIS_SIGNAL_TAPE_GEOJSON_DECIMALS = int(os.getenv("GIS_SIGNAL_TAPE_GEOJSON_DECIMALS", "6") or "6")
GIS_RZD_SIGNAL_GEOJSON_DECIMALS = int(os.getenv("GIS_RZD_SIGNAL_GEOJSON_DECIMALS", "5") or "5")

# GeoDjango library paths (macOS Homebrew).
GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", "/opt/homebrew/lib/libgdal.dylib")
GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH", "/opt/homebrew/lib/libgeos_c.dylib")

# Approval map: mggt_asu.work schema (alias qgis, read-only).
APPROVAL_WORK_SCHEMA = os.getenv("APPROVAL_WORK_SCHEMA", "work")
APPROVAL_WORK_GEOM_COLUMN = os.getenv("APPROVAL_WORK_GEOM_COLUMN", "Geometry")
APPROVAL_WORK_TASKGUID_COLUMN = os.getenv("APPROVAL_WORK_TASKGUID_COLUMN", "TaskGUID")
try:
    APPROVAL_WORK_SOURCE_SRID = int(os.getenv("APPROVAL_WORK_SOURCE_SRID", "980077"))
except (TypeError, ValueError):
    APPROVAL_WORK_SOURCE_SRID = 980077
try:
    APPROVAL_WORK_MAX_FEATURES = int(os.getenv("APPROVAL_WORK_MAX_FEATURES", "5000"))
except (TypeError, ValueError):
    APPROVAL_WORK_MAX_FEATURES = 5000
APPROVAL_ADJACENT_POLY_TABLES = ["YardPoly", "OznPoly", "OdhPoly"]
APPROVAL_ADJACENT_SCHEMA = os.getenv("APPROVAL_ADJACENT_SCHEMA", "master")
APPROVAL_WORK_ROOTID_COLUMN = os.getenv("APPROVAL_WORK_ROOTID_COLUMN", "RootId")

APPROVAL_ATTACHMENT_ALLOWED_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".pdf",
    ".doc",
    ".docx",
}
try:
    APPROVAL_ATTACHMENT_MAX_BYTES = int(os.getenv("APPROVAL_ATTACHMENT_MAX_BYTES", str(10 * 1024 * 1024)))
except (TypeError, ValueError):
    APPROVAL_ATTACHMENT_MAX_BYTES = 10 * 1024 * 1024

# QGIS ingest API: only callable via internal server address (not public reverse-proxy host).
APPROVAL_QGIS_ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "APPROVAL_QGIS_ALLOWED_HOSTS",
        "172.21.197.77,127.0.0.1,localhost,testserver",
    ).split(",")
    if host.strip()
]
APPROVAL_QGIS_API_URL = os.getenv(
    "APPROVAL_QGIS_API_URL",
    "http://172.21.197.77/approval/api/qgis/approves/",
)

# Approval map layer styles (QML sources + generated manifest).
APPROVAL_LAYER_STYLES_ROOT = BASE_DIR / "approval" / "layer_styles"
APPROVAL_LAYER_STYLES_QML_DIR = APPROVAL_LAYER_STYLES_ROOT / "qml"
APPROVAL_LAYER_STYLES_SQL = APPROVAL_LAYER_STYLES_ROOT / "create_work.sql"
APPROVAL_LAYER_STYLES_SVG_SOURCE = APPROVAL_LAYER_STYLES_ROOT / "svg"
APPROVAL_LAYER_STYLES_MANIFEST = BASE_DIR / "approval" / "static" / "approval" / "work_layer_styles.json"
APPROVAL_LAYER_STYLES_SVG_STATIC = BASE_DIR / "approval" / "static" / "approval" / "icons" / "svg"
APPROVAL_LAYER_STYLES_SVG_INDEX = BASE_DIR / "approval" / "static" / "approval" / "svg_index.json"

# Django admin at /admin/ (on VPS set DJANGO_ENABLE_ADMIN=0 in .env).
ENABLE_DJANGO_ADMIN = os.getenv("DJANGO_ENABLE_ADMIN", "1") not in ("0", "false", "False")
