from django.urls import path

from .views import (
    add_object,
    add_recap,
    auto_remove_intersections,
    cancel_pending_entry,
    check_dgi_intersections,
    check_new_object_relations,
    confirm_entry_request_id,
    cut_edited_geometry,
    delete_comment_point,
    delete_owned_object,
    export_geometry,
    export_new_object_geometry,
    home,
    list_comment_points,
    main,
    open_merged_passports,
    open_owned_object,
    prepare_add_object,
    repair_save_geometry,
    save_comment_point,
    save_new_object,
    save_recap_object,
    split_object,
)

urlpatterns = [
    path("", home, name="home"),
    path("add-object/", add_object, name="add_object"),
    path("add-recap/", add_recap, name="add_recap"),
    path("add-object/check-relations/", check_new_object_relations, name="check_new_object_relations"),
    path("add-object/check-dgi-intersections/", check_dgi_intersections, name="check_dgi_intersections"),
    path("add-object/auto-remove-intersections/", auto_remove_intersections, name="auto_remove_intersections"),
    path("add-object/cut-geometry/", cut_edited_geometry, name="cut_edited_geometry"),
    path("add-object/comment-points/", list_comment_points, name="list_comment_points"),
    path("add-object/comment-point/", save_comment_point, name="save_comment_point"),
    path("add-object/comment-point/delete/", delete_comment_point, name="delete_comment_point"),
    path("add-object/export-geometry/", export_new_object_geometry, name="export_new_object_geometry"),
    path("add-object/repair-geometry/", repair_save_geometry, name="repair_save_geometry"),
    path("add-object/save/", save_new_object, name="save_new_object"),
    path("add-recap/save/", save_recap_object, name="save_recap_object"),
    path("owned/open/", open_owned_object, name="open_owned_object"),
    path("owned/merge-passports/", open_merged_passports, name="open_merged_passports"),
    path("owned/confirm-request-id/", confirm_entry_request_id, name="confirm_entry_request_id"),
    path("home/cancel-pending/", cancel_pending_entry, name="cancel_pending_entry"),
    path("add-object/prepare/", prepare_add_object, name="prepare_add_object"),
    path("owned/delete/", delete_owned_object, name="delete_owned_object"),
    path("main/", main, name="main"),
    path("main/export-geometry/", export_geometry, name="export_geometry"),
    path("split-object/", split_object, name="split_object"),
]
