from django.urls import path

from .feedback_views import (
    feedback_attachment_download,
    feedback_list,
    feedback_set_status,
    feedback_submit,
)
from .qgis_api_views import (
    api_qgis_recaps_layer,
    api_qgis_recaps_list,
    api_qgis_requests_layer,
    api_qgis_requests_list,
)
from .registration_views import (
    registration_request,
    registration_request_sent,
    registration_request_set_status,
    registration_requests_export,
    registration_requests_list,
)
from .request_attachment_views import (
    delete_request_attachment,
    download_request_attachment,
    list_request_attachments,
    request_bid_comments,
    request_ods_status,
    upload_request_attachment,
)
from .tile_proxy import proxy_mggt_tile
from .views import (
    actions,
    add_object,
    add_recap,
    auto_remove_intersections,
    cancel_pending_entry,
    check_dgi_intersections,
    check_new_object_relations,
    check_ogx_intersections,
    clear_sup_hood,
    confirm_entry_request_id,
    cut_edited_geometry,
    delete_comment_point,
    delete_owned_object,
    delete_recap_object,
    export_geometry,
    export_new_object_geometry,
    export_recap_geometry,
    find_beskhoz,
    home,
    intersecs_analiz,
    intersecs_analiz_data,
    list_comment_points,
    list_dgi_intersections,
    list_owned_recaps,
    load_map_adjacent_layers,
    load_map_context_layers,
    load_map_layer,
    load_map_reference_layers,
    main,
    open_merged_passports,
    open_owned_object,
    owned_lists_partial,
    personal_export_xlsx,
    personal_object_details,
    prepare_add_object,
    repair_save_geometry,
    resolve_asu_ods_url,
    save_comment_point,
    save_new_object,
    save_recap_object,
    select_sup_hood,
    split_object,
    statistics,
)

urlpatterns = [
    path("", home, name="home"),
    path("personal/", home, name="personal_account"),
    # QGIS API: read-only слои и списки заявок/досъёмов (host allowlist + user, только MGGT/SUP)
    path("api/qgis/requests/", api_qgis_requests_layer, name="api_qgis_requests_layer"),
    path("api/qgis/recaps/", api_qgis_recaps_layer, name="api_qgis_recaps_layer"),
    path("api/qgis/requests/list/", api_qgis_requests_list, name="api_qgis_requests_list"),
    path("api/qgis/recaps/list/", api_qgis_recaps_list, name="api_qgis_recaps_list"),
    path("registration-request/", registration_request, name="registration_request"),
    path("registration-request/sent/", registration_request_sent, name="registration_request_sent"),
    path("registration-requests/", registration_requests_list, name="registration_requests_list"),
    path(
        "registration-requests/export/",
        registration_requests_export,
        name="registration_requests_export",
    ),
    path(
        "registration-requests/<int:pk>/status/",
        registration_request_set_status,
        name="registration_request_set_status",
    ),
    path("statistics/", statistics, name="statistics"),
    path("actions/", actions, name="actions"),
    path("feedback/submit/", feedback_submit, name="feedback_submit"),
    path("feedback/", feedback_list, name="feedback_list"),
    path("feedback/<int:pk>/status/", feedback_set_status, name="feedback_set_status"),
    path(
        "feedback/attachments/<int:attachment_id>/download/",
        feedback_attachment_download,
        name="feedback_attachment_download",
    ),
    path("owned/lists-partial/", owned_lists_partial, name="owned_lists_partial"),
    path("home/select-hood/", select_sup_hood, name="select_sup_hood"),
    path("home/clear-hood/", clear_sup_hood, name="clear_sup_hood"),
    path("add-object/", add_object, name="add_object"),
    path("add-recap/", add_recap, name="add_recap"),
    path("add-object/check-relations/", check_new_object_relations, name="check_new_object_relations"),
    path("add-object/check-dgi-intersections/", check_dgi_intersections, name="check_dgi_intersections"),
    path("add-object/check-ogx-intersections/", check_ogx_intersections, name="check_ogx_intersections"),
    path("intersecs-analiz/", intersecs_analiz, name="intersecs_analiz"),
    path("intersecs-analiz/data/", intersecs_analiz_data, name="intersecs_analiz_data"),
    path("owned/find-beskhoz/", find_beskhoz, name="find_beskhoz"),
    path("owned/resolve-asu-ods-url/", resolve_asu_ods_url, name="resolve_asu_ods_url"),
    path("personal/object-details/", personal_object_details, name="personal_object_details"),
    path("personal/export-xlsx/", personal_export_xlsx, name="personal_export_xlsx"),
    path("add-object/auto-remove-intersections/", auto_remove_intersections, name="auto_remove_intersections"),
    path("add-object/cut-geometry/", cut_edited_geometry, name="cut_edited_geometry"),
    path("add-object/request-status/", request_ods_status, name="request_ods_status"),
    path("add-object/request-comments/", request_bid_comments, name="request_bid_comments"),
    path("add-object/request-attachments/", list_request_attachments, name="list_request_attachments"),
    path("add-object/request-attachments/upload/", upload_request_attachment, name="upload_request_attachment"),
    path(
        "add-object/request-attachments/<int:attachment_id>/download/",
        download_request_attachment,
        name="download_request_attachment",
    ),
    path(
        "add-object/request-attachments/<int:attachment_id>/delete/",
        delete_request_attachment,
        name="delete_request_attachment",
    ),
    path("add-object/comment-point/", save_comment_point, name="save_comment_point"),
    path("add-object/comment-points/", list_comment_points, name="list_comment_points"),
    path("add-object/comment-point/delete/", delete_comment_point, name="delete_comment_point"),
    path("add-object/export-geometry/", export_new_object_geometry, name="export_new_object_geometry"),
    path("add-object/repair-geometry/", repair_save_geometry, name="repair_save_geometry"),
    path("add-object/save/", save_new_object, name="save_new_object"),
    path("add-recap/save/", save_recap_object, name="save_recap_object"),
    path("owned/open/", open_owned_object, name="open_owned_object"),
    path("owned/merge-passports/", open_merged_passports, name="open_merged_passports"),
    path("owned/confirm-request-id/", confirm_entry_request_id, name="confirm_entry_request_id"),
    path("home/cancel-pending/", cancel_pending_entry, name="cancel_pending_entry"),
    path("add-object/prepare/", prepare_add_object, name="prepare_add_object"),
    path("owned/delete/", delete_owned_object, name="delete_owned_object"),
    path("owned/dgi-intersections/", list_dgi_intersections, name="list_dgi_intersections"),
    path("owned/recaps/", list_owned_recaps, name="list_owned_recaps"),
    path("owned/recap/export/", export_recap_geometry, name="export_recap_geometry"),
    path("owned/recap/delete/", delete_recap_object, name="delete_recap_object"),
    path("main/", main, name="main"),
    path("main/load-layer/", load_map_layer, name="load_map_layer"),
    path("main/load-adjacent-layers/", load_map_adjacent_layers, name="load_map_adjacent_layers"),
    path("main/load-reference-layers/", load_map_reference_layers, name="load_map_reference_layers"),
    path("main/load-context-layers/", load_map_context_layers, name="load_map_context_layers"),
    path("main/export-geometry/", export_geometry, name="export_geometry"),
    path("split-object/", split_object, name="split_object"),
    path(
        "tiles/<str:layer>/<int:z>/<int:x>/<int:y>.png",
        proxy_mggt_tile,
        name="mggt_tile",
    ),
]
